#
# Copyright 2017 CERN/Switzerland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sparkoperator
  namespace: sparkoperator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v2.3.0-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/version: v2.3.0-v1alpha1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v2.3.0-v1alpha1
      initializers:
        pending: []  
    spec:
      serviceAccountName: sparkoperator
      volumes:
        - name: client-certs
          secret:
            secretName: spark-secrets
      containers:
      - name: sparkoperator
        image: gitlab-registry.cern.ch/db/spark-service/docker-registry/spark-on-k8s-operator:v1alpha1
        imagePullPolicy: Always
        command: ["/usr/bin/spark-operator"]
        args:
        - -logtostderr
        - -enable-initializer=false
        volumeMounts:
          - name: client-certs
            # Application additionally requires to include 3 spark.kubernetes.authenticate.submission.<auth-files>
            # if you don't need it, remove
            mountPath: '/spark-secrets'
